language: node_js
node_js:
- 10
deploy:
  provider: heroku
  api_key:
    secure: iBlH3gt1zj31PpP4P803GUILAkRqPnVtBZAkOy2jXDAiDf6LmHtjYaWktuUoVdocfhceQ1uz1/a2fL7S5cR5Z9ZVSEwoAA3ljIiPx58pOrh2WRNRES4+uPnZ5mmYEwgqrfywE9ym0gpjafX1RR6Xp3I4T9/yXYbGWBi1yPNmq7/kc/SdwdJ+0rp7+J3Nlk6W7kZmOxbPJ7911Sa496DvyBkZv4JYaXc4xuEf2Uvib13JGIDfshfNfOJMgcuGyKqzZ06DevllgCb27mGQ7taawgN0w+zw1yHr3K5bSiW2EQz4wCg0SBWRKdDbDruE4iohfe7gBaFhvkoLO5UgU02OzZoqJlHVMVYFbIzwaw3JNe8Vue8R6BvnRjFs0h5vZgQsQQ3fKuhBfzyGl1e9mC1f5ER+/EUsZMoCg+YVVZMu41Rw8h9akN45CWQAcGA+KUTaCuC1XwNZ6uo692aCam2HD0CYN3GDcAPeU9s7zw4ZtfwaxfLKgPkD3hkM//rf0JmJMVIHLoq3ILJ15h9Xm3L+iGfVTjC5WtpmysEnXv6i2N5hO31PYoHWszPq/8rr0qf8mKj0Y73fGN9NJ/d/0nz0Gkxuu9B9YLUVLwSnlf/M+sFJA0a4PQiY2qZAG/uXwAhpu9pWG860knjDVdZkKHdhLDEkcP4+aB2aYVuWi50ZuOA=